language: node_js
node_js:
 - '6'

before_install:
  - npm install -g typings@1.3.2 && npm install -g gulp && typings install

script:
  - "gulp build:server && gulp build:clientTs && gulp build:clientTests && npm run-script travis"

after_script:
  - "istanbul cover jasmine-node --captureExceptions dist/server/tests && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
