language: node_js
node_js:
 - '6'
 - '7'

before_install:
  - npm install -g gulp

script:
  - "mkdir dist && chmod 777 dist && gulp build:all && npm run-script travis"

after_script:
  - "istanbul cover jasmine-node --captureExceptions dist/server/tests && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
